FROM python:3.9-slim-buster

WORKDIR /app

COPY ./requirements.txt ./requirements.txt
COPY ./test.csv ./test.csv
RUN pip3 install -r requirements.txt

COPY . .

CMD [ "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000" ]